apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedock-bot
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedock-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedock-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubedock-role
subjects:
- kind: ServiceAccount
  name: kubedock-bot
  namespace: kube-system
